"""Loading documents from the workspace, and composing the per-tenant effective view.

    workspace/
      profiles/<id>.yaml              app profiles (per vendor product/version)
      tenants/<id>.yaml               tenant bindings
      policies/<id>.yaml              safety policies
      goals/<name>.yaml               discovery goals
      capabilities/<id>/<ver>.yaml    the capability store (reviewed artifacts, in git)

`effective_profile` / `effective_capability` apply a tenant's layers (vocabulary, extra
conditions and screens, targeted overrides) at load time. Nothing on disk is modified.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, TypeVar

import yaml

from .schema import AppProfile, Capability, GoalSpec, Model, Policy, TenantBinding

M = TypeVar("M", bound=Model)
_ENV_RE = re.compile(r"\$\{(\w+)(?::-([^}]*))?\}")


def workspace() -> Path:
    return Path(os.environ.get("UNDERSTUDY_HOME", Path.cwd())).resolve()


def _expand_env(x: Any) -> Any:
    if isinstance(x, str):
        return _ENV_RE.sub(lambda m: os.environ.get(m.group(1), m.group(2) or ""), x)
    if isinstance(x, dict):
        return {k: _expand_env(v) for k, v in x.items()}
    if isinstance(x, list):
        return [_expand_env(v) for v in x]
    return x


def read_yaml(path: Path) -> Any:
    with open(path) as f:
        return _expand_env(yaml.safe_load(f))


def load(model: type[M], path: Path) -> M:
    return model.model_validate(read_yaml(path))


class _Dumper(yaml.SafeDumper):
    pass


def _str_repr(dumper: yaml.SafeDumper, s: str) -> yaml.ScalarNode:
    style = "|" if "\n" in s else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", s, style=style)


_Dumper.add_representer(str, _str_repr)


def to_yaml(m: Model | dict, header: str | None = None) -> str:
    body = yaml.dump(m.dump() if isinstance(m, Model) else m, Dumper=_Dumper, sort_keys=False, width=110, allow_unicode=True)
    return (header.rstrip() + "\n" if header else "") + body


def load_profile(profile_id: str, root: Path | None = None) -> AppProfile:
    return load(AppProfile, (root or workspace()) / "profiles" / f"{profile_id}.yaml")


def load_tenant(tenant_id: str, root: Path | None = None) -> TenantBinding:
    return load(TenantBinding, (root or workspace()) / "tenants" / f"{tenant_id}.yaml")


def load_policy(policy_id: str = "default", root: Path | None = None) -> Policy:
    return load(Policy, (root or workspace()) / "policies" / f"{policy_id}.yaml")


def load_goal(path: str | Path) -> GoalSpec:
    p = Path(path)
    if not p.exists():
        p = workspace() / "goals" / f"{path}.yaml"
    return load(GoalSpec, p)


# --------------------------------------------------------------------------- capability store


def _semver_key(v: str) -> tuple[int, ...]:
    return tuple(int(x) for x in v.split("."))


class CapabilityStore:
    """Capabilities are plain YAML files in git: review is a diff, approval is a commit."""

    def __init__(self, root: Path | None = None):
        self.root = (root or workspace()) / "capabilities"

    def versions(self, cap_id: str) -> list[str]:
        d = self.root / cap_id
        if not d.exists():
            return []
        return sorted((p.stem for p in d.glob("*.yaml")), key=_semver_key)

    def ids(self) -> list[str]:
        return sorted(p.name for p in self.root.iterdir() if p.is_dir()) if self.root.exists() else []

    def path(self, cap_id: str, version: str) -> Path:
        return self.root / cap_id / f"{version}.yaml"

    def load(self, ref: str) -> Capability:
        """`ref` is 'id', 'id@version', or a path to a YAML file."""
        p = Path(ref)
        if p.suffix in (".yaml", ".yml") and p.exists():
            return load(Capability, p)
        cap_id, _, version = ref.partition("@")
        if not version:
            vs = self.versions(cap_id)
            if not vs:
                raise FileNotFoundError(f"no capability {cap_id!r} in {self.root}")
            version = vs[-1]
        return load(Capability, self.path(cap_id, version))

    def save(self, cap: Capability) -> Path:
        path = self.path(cap.id, cap.version)
        path.parent.mkdir(parents=True, exist_ok=True)
        header = (
            f"# {cap.title}\n# Capability artifact - understudy/capability@1. Generated by the compiler, then reviewed.\n"
            f"# content hash: {cap.content_hash()}"
        )
        path.write_text(to_yaml(cap, header))
        return path

    def next_version(self, cap: Capability) -> str:
        """Semver: contract changes (inputs/outputs/outcomes) bump major, flow changes bump minor."""
        vs = self.versions(cap.id)
        if not vs:
            return "1.0.0"
        prev = self.load(f"{cap.id}@{vs[-1]}")
        major, minor, _ = _semver_key(vs[-1])
        contract = lambda c: {k: c.dump().get(k) for k in ("inputs", "outputs", "outcomes")}  # noqa: E731
        if contract(prev) != contract(cap):
            return f"{major + 1}.0.0"
        return f"{major}.{minor + 1}.0"


# --------------------------------------------------------------------------- tenant composition

_TEXT_KEYS = {"name", "label", "text", "column", "option", "message"}


def _apply_vocabulary(x: Any, vocab: dict[str, str], hits: set[str], key: str | None = None) -> Any:
    """Swap vendor-default display text for the tenant's, only where the whole string is display text."""
    if not vocab:
        return x
    if isinstance(x, str):
        if key in _TEXT_KEYS and x in vocab:
            hits.add(f"{x} -> {vocab[x]}")
            return vocab[x]
        return x
    if isinstance(x, list):
        if key == "headers":
            out = []
            for v in x:
                if isinstance(v, str) and v in vocab:
                    hits.add(f"{v} -> {vocab[v]}")
                    out.append(vocab[v])
                else:
                    out.append(v)
            return out
        return [_apply_vocabulary(v, vocab, hits, key) for v in x]
    if isinstance(x, dict):
        if "value" in x and "mode" in x and key in _TEXT_KEYS and isinstance(x["value"], str) and x["value"] in vocab:
            hits.add(f"{x['value']} -> {vocab[x['value']]}")
            return {**x, "value": vocab[x["value"]]}
        if key == "row":  # table_cell row keys: both the column header and the key value are display text
            out = {}
            for k, v in x.items():
                nk = vocab.get(k, k)
                if nk != k:
                    hits.add(f"{k} -> {nk}")
                nv = _apply_vocabulary(v, vocab, hits, "text")
                out[nk] = nv
            return out
        return {k: _apply_vocabulary(v, vocab, hits, k) for k, v in x.items()}
    return x


def effective_profile(profile: AppProfile, tenant: TenantBinding) -> AppProfile:
    body = profile.dump()
    by_id = {c["id"]: c for c in body["conditions"]}
    for c in tenant.conditions:
        by_id[c.id] = c.dump()
    body["conditions"] = sorted(by_id.values(), key=lambda c: c.get("priority", 50))
    screens = {s["id"]: s for s in body["screens"]}
    for s in tenant.screens:
        screens[s.id] = s.dump()
    body["screens"] = list(screens.values())
    hits: set[str] = set()
    body = _apply_vocabulary(body, tenant.vocabulary, hits)
    return AppProfile.model_validate(body)


def effective_capability(cap: Capability, tenant: TenantBinding) -> tuple[Capability, list[str]]:
    """The capability as it should run for this tenant, plus a list of what was changed."""
    body = cap.dump()
    applied: list[str] = []
    hits: set[str] = set()
    for field in ("steps", "outputs", "success"):
        body[field] = _apply_vocabulary(body[field], tenant.vocabulary, hits, field)
    applied += [f"vocabulary: {h}" for h in sorted(hits)]
    ov = tenant.capability_overrides.get(cap.id)
    if ov:
        for key, target in ov.targets.items():
            if key.startswith("output:"):
                name = key.split(":", 1)[1]
                body["outputs"][name]["source"] = target.dump()
            else:
                step = next((s for s in body["steps"] if s["id"] == key), None)
                if step is None:
                    raise KeyError(f"tenant {tenant.id} overrides unknown step {key!r} of {cap.id}")
                step["target"] = target.dump()
            applied.append(f"override: {key} ({ov.reason})")
    return Capability.model_validate(body), applied
